# Generated by Django 4.2.15 on 2024-08-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dvdag', upload_to=''),
            preserve_default=False,
        ),
    ]
